"""Tests for PDF report generator."""

from __future__ import annotations

import pytest
from pathlib import Path

from vibee_hacker.reports.pdf_report import PdfReporter
from vibee_hacker.core.models import Result, Severity, Target


def _make_result(sev: Severity, title: str = "Finding", plugin: str = "test") -> Result:
    return Result(
        plugin_name=plugin,
        base_severity=sev,
        title=title,
        description=f"Description for {title}",
        recommendation="Fix it.",
        endpoint="https://example.com/test",
    )


class TestPdfReporter:
    """Tests for PdfReporter (text fallback path — no reportlab required)."""

    @pytest.fixture
    def reporter(self):
        return PdfReporter()

    @pytest.fixture
    def target(self):
        return Target(url="https://example.com")

    def test_output_file_created(self, reporter, target, tmp_path):
        """generate() creates a file at the given output path."""
        out = str(tmp_path / "report.pdf")
        reporter.generate([], target, out)
        assert Path(out).exists()

    def test_generate_text_fallback(self, reporter, target, tmp_path, monkeypatch):
        """_generate_text is called when reportlab is unavailable."""
        # Force ImportError so the fallback is always exercised
        import builtins
        real_import = builtins.__import__

        def mock_import(name, *args, **kwargs):
            if name == "reportlab" or name.startswith("reportlab."):
                raise ImportError("reportlab not available")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr(builtins, "__import__", mock_import)

        out = str(tmp_path / "report.pdf")
        result = reporter.generate([_make_result(Severity.HIGH)], target, out)
        assert result == out
        assert Path(out).exists()

    def test_text_report_content(self, reporter, target, tmp_path):
        """Text report contains expected header and target info."""
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([_make_result(Severity.HIGH, "SQL Injection")], target, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "VIBEE-Hacker Security Scan Report" in content
        assert "https://example.com" in content
        assert "SQL Injection" in content
        assert "Total Findings: 1" in content
        assert "Generated by VIBEE-Hacker" in content

    def test_severity_counts(self, reporter, target, tmp_path):
        """Text report shows correct per-severity counts."""
        results = [
            _make_result(Severity.CRITICAL, "Critical Bug"),
            _make_result(Severity.HIGH, "High Bug 1"),
            _make_result(Severity.HIGH, "High Bug 2"),
            _make_result(Severity.LOW, "Low Bug"),
        ]
        out = str(tmp_path / "report.pdf")
        reporter._generate_text(results, target, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "CRITICAL: 1" in content
        assert "HIGH: 2" in content
        assert "LOW: 1" in content
        assert "Total Findings: 4" in content

    def test_empty_results(self, reporter, target, tmp_path):
        """Report with no results still generates valid file."""
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([], target, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "Total Findings: 0" in content
        assert "VIBEE-Hacker Security Scan Report" in content

    def test_whitebox_target(self, reporter, tmp_path):
        """Target with a path (not URL) appears correctly in report."""
        t = Target(path="/code/myrepo", mode="whitebox")
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([_make_result(Severity.MEDIUM)], t, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "/code/myrepo" in content

    def test_unknown_target(self, reporter, tmp_path):
        """Target with neither url nor path falls back to 'Unknown'."""
        t = Target()
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([], t, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "Unknown" in content

    def test_generate_returns_output_path(self, reporter, target, tmp_path):
        """generate() returns the output path string."""
        out = str(tmp_path / "scan.pdf")
        returned = reporter.generate([], target, out)
        assert returned == out

    def test_endpoint_in_report(self, reporter, target, tmp_path):
        """Endpoint URL from Result appears in text report."""
        r = _make_result(Severity.HIGH, "Auth bypass")
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([r], target, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "https://example.com/test" in content

    def test_recommendation_in_report(self, reporter, target, tmp_path):
        """Recommendation text from Result appears in text report."""
        r = _make_result(Severity.MEDIUM, "Misconfiguration")
        out = str(tmp_path / "report.pdf")
        reporter._generate_text([r], target, out)
        content = Path(out).read_text(encoding="utf-8")
        assert "Fix it." in content
