"""GitHub Autofix PR generator: creates fix patches from scan results."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

from vibee_hacker.core.models import Result
from vibee_hacker.core.autofix import AutofixEngine, FixSuggestion

logger = logging.getLogger(__name__)


@dataclass
class FixPatch:
    """A single file fix patch."""
    file_path: str
    original_line: str
    fixed_line: str
    line_number: int = 0
    description: str = ""
    rule_id: str = ""


@dataclass
class AutofixPR:
    """A complete autofix pull request."""
    title: str
    body: str
    branch_name: str
    patches: list[FixPatch] = field(default_factory=list)
    findings_fixed: int = 0

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "body": self.body,
            "branch_name": self.branch_name,
            "patches": [{"file": p.file_path, "line": p.line_number, "original": p.original_line, "fixed": p.fixed_line, "description": p.description} for p in self.patches],
            "findings_fixed": self.findings_fixed,
        }

    def generate_diff(self) -> str:
        """Generate unified diff format."""
        diffs = []
        for patch in self.patches:
            diffs.append(f"--- a/{patch.file_path}")
            diffs.append(f"+++ b/{patch.file_path}")
            diffs.append(f"@@ -{patch.line_number},1 +{patch.line_number},1 @@")
            diffs.append(f"-{patch.original_line}")
            diffs.append(f"+{patch.fixed_line}")
        return "\n".join(diffs)

    def generate_commit_message(self) -> str:
        rules = set(p.rule_id for p in self.patches if p.rule_id)
        return f"fix(security): auto-fix {self.findings_fixed} vulnerabilities ({', '.join(sorted(rules))})"

    def generate_pr_body(self) -> str:
        lines = [
            "## Security Autofix",
            "",
            f"**Findings fixed:** {self.findings_fixed}",
            "",
            "### Changes",
            "",
        ]
        for p in self.patches:
            lines.append(f"- **{p.file_path}:{p.line_number}** — {p.description}")
        lines.extend([
            "",
            "---",
            "Generated by VIBEE-Hacker Autofix",
        ])
        return "\n".join(lines)


class AutofixPRGenerator:
    """Generates autofix PRs from scan results."""

    def __init__(self, repo_path: str = "."):
        self.repo_path = Path(repo_path)
        self._autofix = AutofixEngine()

    def generate(self, results: list[Result], language: str = "python") -> AutofixPR | None:
        """Generate an autofix PR from scan results."""
        patches = []

        for result in results:
            rule_id = result.rule_id or result.plugin_name or ""
            fixes = self._autofix.get_fixes(rule_id, language=language)
            if not fixes:
                continue

            fix = fixes[0]  # Use first available fix
            # Try to find the vulnerable pattern in the source file
            if result.endpoint and self.repo_path.exists():
                file_patches = self._find_and_patch(result.endpoint, fix)
                patches.extend(file_patches)

        if not patches:
            return None

        pr = AutofixPR(
            title=f"fix(security): auto-fix {len(patches)} vulnerabilities",
            body="",
            branch_name=f"autofix/vibee-{len(patches)}-fixes",
            patches=patches,
            findings_fixed=len(patches),
        )
        pr.body = pr.generate_pr_body()
        return pr

    def _find_and_patch(self, filepath: str, fix: FixSuggestion) -> list[FixPatch]:
        """Search file for vulnerable pattern and create patch."""
        patches = []
        target = self.repo_path / filepath
        if not target.is_file():
            # Try as-is path
            target = Path(filepath)
        if not target.is_file():
            return []

        try:
            lines = target.read_text(encoding="utf-8").split("\n")
        except (OSError, UnicodeDecodeError):
            return []

        # Search for the vulnerable pattern (before)
        before_first_line = fix.before.split("\n")[0].strip()
        for i, line in enumerate(lines):
            if before_first_line in line.strip():
                patches.append(FixPatch(
                    file_path=str(filepath),
                    original_line=line.strip(),
                    fixed_line=fix.after.split("\n")[0].strip(),
                    line_number=i + 1,
                    description=fix.description,
                    rule_id=fix.rule_id,
                ))
                break  # One patch per fix

        return patches

    def apply_patches(self, pr: AutofixPR) -> int:
        """Apply patches to files. Returns count of files modified."""
        modified = 0
        for patch in pr.patches:
            target = self.repo_path / patch.file_path
            if not target.is_file():
                target = Path(patch.file_path)
            if not target.is_file():
                continue

            try:
                content = target.read_text(encoding="utf-8")
                if patch.original_line in content:
                    content = content.replace(patch.original_line, patch.fixed_line, 1)
                    target.write_text(content, encoding="utf-8")
                    modified += 1
            except (OSError, UnicodeDecodeError):
                continue

        return modified

    def generate_script(self, pr: AutofixPR) -> str:
        """Generate a shell script to create the PR via git/gh."""
        lines = [
            "#!/bin/bash",
            f"git checkout -b {pr.branch_name}",
        ]
        for patch in pr.patches:
            escaped_orig = patch.original_line.replace("'", "'\\''")
            escaped_fix = patch.fixed_line.replace("'", "'\\''")
            lines.append(f"sed -i 's|{escaped_orig}|{escaped_fix}|' {patch.file_path}")
        lines.extend([
            "git add -A",
            f"git commit -m '{pr.generate_commit_message()}'",
            f"git push origin {pr.branch_name}",
            f"gh pr create --title '{pr.title}' --body '{pr.body[:500]}'",
        ])
        return "\n".join(lines)
